[package]
edition = "2024"
rust-version = "1.96.0"
name = "pico-io-bridge"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/ulso/pico-io-bridge"
resolver = "2"

[features]
default = ["board-adafruit-rp2040-can"]
board-adafruit-rp2040-can = ["mdns", "dhcp-server", "mcp25625", "i2c"]
board-adafruit-feather-rp2040 = ["mdns", "dhcp-server", "i2c", "embassy-rp/boot2-generic-03h"]
board-adafruit-rp2040-usb-host = [
    "mdns",
    "dhcp-server",
    "i2c",
    "dep:embassy-rp-pio-usb-host",
    "embassy-rp-pio-usb-host/embassy-usb-host",
    "dep:embassy-usb-host",
    "embassy-rp/boot2-generic-03h",
]
board-adafruit-kb2040 = ["mdns", "dhcp-server", "i2c"]
mdns = ["dep:embedded-alloc", "dep:hick-embassy", "dep:mdns-proto", "hick-embassy/no-atomic", "mdns-proto/no-atomic", "embassy-net/mdns"]
dhcp-server = ["dep:leasehund", "leasehund/defmt", "embassy-net/dhcpv4"]
can = ["dep:embedded-hal-1", "dep:embedded-hal-bus", "dep:mcp25xx", "dep:nb"]
i2c = ["dep:vl53l4cd"]
mcp2515 = ["can", "mcp25xx/mcp2515"]
mcp25625 = ["can", "mcp25xx/mcp25625"]

[dependencies]
embassy-embedded-hal = { version = "0.6.0", features = ["defmt"] }
embassy-sync = { version = "0.8.0", features = ["defmt"] }
embassy-executor = {  version = "0.10.0", features = ["platform-cortex-m", "executor-thread", "executor-interrupt", "defmt"] }
embassy-time = { version = "0.5.1", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-rp = { version = "0.10.0", features = ["defmt", "unstable-pac", "time-driver", "critical-section-impl", "rp2040"] }
embassy-futures = { version = "0.1.2"}
embassy-usb = { version = "0.6.0", default-features = false, features = ["defmt", "max-interface-count-4"] }
embassy-usb-host = { version = "=0.1.0", default-features = false, optional = true }
embassy-rp-pio-usb-host = {
    git = "https://github.com/ulso/embassy-rp-pio-usb-host",
    rev = "2fa4136ae9a9e0ec2714052069488c27b031b529",
    default-features = false,
    optional = true,
}
usbd-hid = "0.10.0"
embassy-net = { version = "0.9.1", features = ["defmt", "tcp", "udp", "medium-ethernet", "multicast", "proto-ipv4", "proto-ipv6", "auto-icmp-echo-reply"] }

defmt = "1.1.0"
defmt-rtt = "1.2.0"
fixed = "1.31.0"
fixed-macro = "1.2.0"

cortex-m = { version = "0.7.7", features = ["inline-asm"] }
cortex-m-rt = "0.7.5"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
futures = { version = "0.3.31", default-features = false, features = ["async-await", "cfg-target-has-atomic", "unstable"] }
heapless = "0.9.3"
embedded-alloc = { version = "0.6.0", optional = true }

embedded-hal-1 = { package = "embedded-hal", version = "=1.0.0", optional = true }
embedded-hal-async = "1.0.0"
embedded-hal-bus = { version = "0.3.0", features = ["async"], optional = true }
embedded-io-async = { version = "0.7.0", features = ["defmt"] }
embedded-storage = { version = "0.3.1" }
static_cell = "2.1.1"
portable-atomic = { version = "1.13.1", features = ["critical-section"] }
log = "0.4.32"
pio-proc = "0.3.0"
pio = "0.3.0"
rand = { version = "0.10.1", default-features = false }
rand_core = { version = "0.10.1", default-features = false }
hick-embassy = { version = "0.2", default-features = false, optional = true }
mdns-proto = { version = "0.3", default-features = false, optional = true }
leasehund = { version = "0.5.2", default-features = false, optional = true }
mcp25xx = { version = "0.4.0", optional = true }
nb = { version = "1.1.0", optional = true }
microscpi = { version = "0.6.0", features = ["defmt"] }
vl53l4cd = { version = "0.4.0", default-features = false, optional = true }

[profile.release]
debug = true
lto = "fat"
opt-level = "s"
codegen-units = 1

# Below configs are here to mute the rust-analyzer error.
# "Can't find crate for 'test'" as this is a no_std project
[[bin]]
name = "pico-io-bridge"
test = false
bench = false
